export const APARTMENT_LIST_REQUEST= 'APARTMENT_LIST_REQUEST'
export const APARTMENT_LIST_SUCCESS= 'APARTMENT_LIST_SUCCESS'
export const APARTMENT_LIST_FAIL= 'APARTMENT_LIST_FAIL'
export const APARTMENT_LIST_RESET= 'APARTMENT_LIST_RESET'

export const APARTMENT_DETAILS_REQUEST= 'APARTMENT_DETAILS_REQUEST'
export const APARTMENT_DETAILS_SUCCESS= 'APARTMENT_DETAILS_SUCCESS'
export const APARTMENT_DETAILS_FAIL= 'APARTMENT_DETAILS_FAIL'

export const APARTMENT_DELETE_REQUEST= 'APARTMENT_DELETE_REQUEST'
export const APARTMENT_DELETE_SUCCESS= 'APARTMENT_DELETE_SUCCESS'
export const APARTMENT_DELETE_FAIL= 'APARTMENT_DELETE_FAIL'

export const APARTMENT_CREATE_REQUEST= 'APARTMENT_CREATE_REQUEST'
export const APARTMENT_CREATE_SUCCESS= 'APARTMENT_CREATE_SUCCESS'
export const APARTMENT_CREATE_FAIL= 'APARTMENT_CREATE_FAIL'
export const APARTMENT_CREATE_RESET= 'APARTMENT_CREATE_RESET'

export const APARTMENT_UPDATE_REQUEST = 'APARTMENT_UPDATE_REQUEST'
export const APARTMENT_UPDATE_SUCCESS = 'APARTMENT_UPDATE_SUCCESS'
export const APARTMENT_UPDATE_FAIL = 'APARTMENT_UPDATE_FAIL'
export const APARTMENT_UPDATE_RESET = 'APARTMENT_UPDATE_RESET'