export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET'

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

export const BOOKING_PAY_REQUEST = 'BOOKING_PAY_REQUEST'
export const BOOKING_PAY_SUCCESS = 'BOOKING_PAY_SUCCESS'
export const BOOKING_PAY_FAIL = 'BOOKING_PAY_FAIL'
export const BOOKING_PAY_RESET = 'BOOKING_PAY_RESET'